package com.caliarena.http

import io.swagger.v3.core.util.Yaml
import io.swagger.v3.oas.models.OpenAPI
import org.springdoc.core.customizers.OpenApiCustomizer
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration

/**
 * Serves the hand-written spec from `docs/openapi.yaml` (copied into the classpath
 * root by `processResources`) instead of the spec auto-generated by springdoc, so
 * the Swagger UI shows the complete API (schemas, problems, SSE, etc.).
 */
@Configuration
class StaticOpenApiCustomizer {
    @Bean
    fun staticOpenApi(): OpenApiCustomizer =
        OpenApiCustomizer { openApi ->
            val resource = javaClass.getResourceAsStream("/openapi.yaml")
                ?: return@OpenApiCustomizer
            val spec = Yaml.mapper().readValue(resource, OpenAPI::class.java)
            openApi
                .info(spec.info)
                .servers(spec.servers)
                .tags(spec.tags)
                .paths(spec.paths)
                .components(spec.components)
        }
}