services:
  ubuntu:
    container_name: ubuntu
    image: caliarena-ubuntu
    tty: true

  caliarena-postgres:
    container_name: caliarena-postgres
    image: caliarena-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  caliarena-jvm:
    container_name: caliarena-jvm
    hostname: caliarena-jvm
    image: caliarena-jvm
    environment:
      PORT: 8080
      DB_URL: ${DB_URL}
    ports:
      - "8080:8080"