FROM node:20-alpine AS build
WORKDIR /app
COPY ./web-app/package*.json ./
RUN npm ci
COPY ./web-app/ ./
RUN npm run build

FROM nginx
COPY ./back-end/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 4000
CMD ["nginx", "-g", "daemon off;"]