
# This Database configuration is for development only. It is not intended for production use.
# The Database should be running on localhost.
spring.datasource.url=jdbc:postgresql://localhost:5432/cali_db
spring.datasource.username=cali_db
spring.datasource.password=cali123
spring.datasource.driver-class-name=org.postgresql.Driver


logging.level.com.caliarena.service.sse=DEBUG

#spring.jpa.show-sql=true
#logging.level.org.springframework.jdbc=DEBUG
#logging.level.com.zaxxer.hikari=DEBUG

# Spring Boot Actuator
#management.endpoints.web.exposure.include=health
#management.endpoint.health.show-details=always

# Spring Boot WebSockets with
logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG