
spring.profiles.active=prod

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Virtual Threads for better concurrency handling
spring.threads.virtual.enabled=true