name: Kotlin CI

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back-end

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Oracle JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: '21'
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run tests
        run: ./gradlew :service:test :repo-jpa:test --rerun-tasks